"use client";
import {FormEvent,useState} from "react";import {useRouter} from "next/navigation";import {useLanguage} from "./language-provider";import {t} from "@/lib/i18n";
const examples=[
["What evidence supports preemptive TEVAR for uncomplicated type B aortic dissection?","合併症のないB型大動脈解離に対する先制的TEVARを支持するエビデンスは何ですか？"],
["Is there comparative evidence supporting distal-first TEVAR deployment?","遠位側からのTEVAR展開を支持する比較エビデンスはありますか？"],
["How do false lumen embolization and F/BEVAR compare for chronic post-dissection aneurysmal degeneration?","慢性解離後の瘤化に対して、偽腔塞栓術とF/BEVARはどう比較されますか？"],
["What do current guidelines recommend for endovascular treatment in HTAD?","現在のガイドラインはHTADの血管内治療をどのように推奨していますか？"]];
const modes=[
["Ask Aortic","Focused evidence review","大動脈について質問","焦点を絞ったエビデンスレビュー"],
["Compare Strategies","Side-by-side options","治療戦略を比較","選択肢を並べて比較"],
["Create Slides","Presentation-ready structure","スライド作成","発表向けの構成"],
["Guideline Mode","Regional guidance view","ガイドラインモード","地域別ガイダンス"],
["Research Mode","Gaps and study framing","リサーチモード","研究課題と構想"]];
export function HomeClient(){const{language}=useLanguage();const router=useRouter();const[q,setQ]=useState("");const[mode,setMode]=useState(modes[0][0]);function submit(e:FormEvent){e.preventDefault();if(!q.trim())return;localStorage.setItem("aes-question",q.trim());localStorage.setItem("aes-mode",mode);router.push('/results')};return <div className="shell py-14"><section className="max-w-4xl"><div className="eyebrow">{t(language,"Specialist evidence workspace","専門医向けエビデンスワークスペース")}</div><h1 className="mt-4 text-4xl md:text-6xl font-semibold tracking-tight max-w-3xl">{t(language,"Evidence for complex aortic decisions","複雑な大動脈治療判断のためのエビデンス")}</h1><p className="mt-6 text-lg leading-8 text-slate-600 max-w-3xl">{t(language,"Search published evidence, guidelines, device information, and regulatory sources, then convert the findings into specialist-ready outputs.","論文、ガイドライン、デバイス情報、規制情報を検索し、専門医向けの成果物へ変換します。")}</p></section><form onSubmit={submit} className="card mt-12 p-6 md:p-8"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-950">⚠ {t(language,"Do not enter patient names, medical record numbers, dates of birth, or other identifiable information.","患者氏名、診療録番号、生年月日など、個人を特定できる情報は入力しないでください。")}</div><label htmlFor="question" className="block mt-7 mb-3 font-bold">{t(language,"Your question","質問")}</label><textarea id="question" maxLength={1500} value={q} onChange={e=>setQ(e.target.value)} rows={5} className="w-full resize-y rounded-xl border border-slate-300 p-4 text-lg" placeholder={t(language,"Ask a specialist aortic question...","大動脈治療に関する専門的な質問を入力してください...")}/><div className="text-right text-xs text-slate-500">{q.length} / 1500</div><div className="mt-7 font-bold">{t(language,"Choose a workflow","ワークフローを選択")}</div><div className="mt-3 grid gap-3 md:grid-cols-5">{modes.map(m=><button type="button" aria-pressed={mode===m[0]} onClick={()=>setMode(m[0])} key={m[0]} className={`rounded-xl border p-4 text-left ${mode===m[0]?'border-blue-700 bg-blue-50 ring-1 ring-blue-700':'border-slate-200 bg-white'}`}><b className="text-sm">{t(language,m[0],m[2])}</b><span className="mt-2 block text-xs leading-5 text-slate-500">{t(language,m[1],m[3])}</span></button>)}</div><button disabled={!q.trim()} className="btn mt-7 text-base">{t(language,"Review Evidence","エビデンスを確認")} →</button></form><section className="mt-10"><h2 className="text-lg font-bold">{t(language,"Example questions","質問例")}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{examples.map((x,i)=><button onClick={()=>setQ(t(language,x[0],x[1]))} className="card p-4 text-left text-sm leading-6 hover:border-blue-400" key={i}>{t(language,x[0],x[1])}</button>)}</div></section></div>}
