"use client";
import { useMemo, useState } from "react";
import { useLanguage } from "./language-provider";
import { t } from "@/lib/i18n";
import type { DuplicateCandidate } from "@/lib/canonical-evidence/duplicate-candidates";
import type { MigrationCandidateReport, MigrationDecisionFile, MigrationResolution } from "@/lib/migration-review-model";
import { exactCandidateIds, migrationCandidateId } from "@/lib/migration-review-model";

const classes = ["likely_equivalent", "related_but_not_equivalent", "conflicting", "insufficient_information"] as const;
const fields = ["wording", "quotation", "location", "interpretation", "limitation", "reviewer", "review_date", "decision", "verification_status"] as const;
const choices: Array<{ value: MigrationResolution; en: string; ja: string }> = [{ value: "same_canonical_evidence_item", en: "Same canonical evidence item", ja: "同一の正規エビデンス項目" }, { value: "keep_separate_evidence_items", en: "Keep as separate evidence items", ja: "別々のエビデンス項目として保持" }, { value: "needs_further_review", en: "Needs further review", ja: "追加レビューが必要" }];
const label = (value: string) => value.replaceAll("_", " ").replace(/^./, character => character.toUpperCase());
const display = (value: unknown) => Array.isArray(value) ? value.length ? <ul className="list-disc space-y-1 pl-5">{value.map((item, index) => <li key={index}>{String(item)}</li>)}</ul> : <span className="text-slate-400">None</span> : value ? String(value) : <span className="text-slate-400">Not recorded</span>;

function CandidateCard({ candidate, saved, onSaved }: { candidate: DuplicateCandidate; saved?: MigrationResolution; onSaved: (file: MigrationDecisionFile) => void }) {
  const { language } = useLanguage(); const id = migrationCandidateId(candidate); const [resolution, setResolution] = useState<MigrationResolution | "">(saved ?? ""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function save() { if (!resolution) return; setSaving(true); setMessage(""); try { const response = await fetch("/api/migration/q02-q03", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "individual", candidateId: id, resolution }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); onSaved(body); setMessage(t(language, "Migration decision saved. No evidence was merged.", "移行判断を保存しました。エビデンスは統合されていません。")); } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed"); } finally { setSaving(false); } }
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-bold">{candidate.left.itemId} ↔ {candidate.right.itemId}</h4><p className="mt-1 text-xs text-slate-500">{candidate.left.legacyAlias} · {candidate.right.legacyAlias}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{label(candidate.classification)}</span></div>
  <div className="mt-5 overflow-x-auto"><div className="min-w-[44rem]"><div className="grid grid-cols-[9rem_1fr_1fr] gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200"><div className="bg-slate-50 p-3 font-bold">{t(language,"Field","項目")}</div><div className="bg-blue-50 p-3 font-bold">Q02 · {candidate.left.itemId}</div><div className="bg-amber-50 p-3 font-bold">Q03 · {candidate.right.itemId}</div>{fields.flatMap(field => { const comparison = candidate.comparisons.find(item => item.field === field); return [<div key={`${field}-label`} className="bg-slate-50 p-3 text-sm font-semibold">{label(field)}{comparison?.equal && <span className="ml-2 text-xs text-emerald-700">{t(language,"Same","一致")}</span>}</div>, <div key={`${field}-left`} className="break-words bg-white p-3 text-sm leading-6">{display(comparison?.left)}</div>, <div key={`${field}-right`} className="break-words bg-white p-3 text-sm leading-6">{display(comparison?.right)}</div>]; })}</div></div></div>
  <fieldset className="mt-5"><legend className="font-bold">{t(language,"Manual resolution","手動解決")}</legend><div className="mt-3 grid gap-2 lg:grid-cols-3">{choices.map(choice => <label key={choice.value} className={`flex min-h-12 items-center gap-3 rounded-xl border p-3 text-sm font-semibold ${resolution===choice.value?"border-blue-600 bg-blue-50":"border-slate-200"}`}><input type="radio" name={`resolution-${id}`} value={choice.value} checked={resolution===choice.value} onChange={() => setResolution(choice.value)}/>{t(language,choice.en,choice.ja)}</label>)}</div></fieldset>
  <div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" className="btn" disabled={!resolution||saving} onClick={save}>{saving?t(language,"Saving…","保存中…"):t(language,"Save manual resolution","手動解決を保存")}</button><span className="text-sm text-slate-600">{t(language,"This records a migration decision only; it does not merge evidence.","移行判断のみを記録し、エビデンスは統合しません。")}</span></div>{message&&<p role="status" className="mt-3 rounded-lg bg-slate-100 p-3 text-sm font-semibold">{message}</p>}</article>;
}

export function MigrationReviewClient({ report, initialDecisions }: { report: MigrationCandidateReport; initialDecisions: MigrationDecisionFile }) {
  const { language } = useLanguage(); const [decisions, setDecisions] = useState(initialDecisions); const [bulkConfirmed, setBulkConfirmed] = useState(false); const [bulkMessage, setBulkMessage] = useState(""); const exactIds = useMemo(() => exactCandidateIds(report), [report]); const sources = report.sourceComparisons.map(item => item.sourceId);
  async function bulkSave() { setBulkMessage(""); try { const response = await fetch("/api/migration/q02-q03", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "exact_bulk", candidateIds: exactIds, confirmed: bulkConfirmed }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setDecisions(body); setBulkMessage(t(language,"Exact-match decisions saved. No canonical records were created.","完全一致候補の判断を保存しました。正規レコードは作成されていません。")); } catch (error) { setBulkMessage(error instanceof Error ? error.message : "Save failed"); } }
  return <main className="shell py-12"><div className="eyebrow">{t(language,"Canonical migration review","正規移行レビュー")}</div><h1 className="mt-3 text-3xl font-semibold">Q02/Q03 {t(language,"candidate review","候補レビュー")}</h1><div className="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-950">{t(language,"Read-only evidence comparison. Decisions saved here do not modify, approve, or merge medical evidence.","読み取り専用のエビデンス比較です。ここで保存する判断は、医療エビデンスの変更・承認・統合を行いません。")}</div>
  <section className="card mt-7 p-6"><h2 className="text-xl font-bold">{t(language,"Deterministically exact bulk confirmation","決定論的完全一致の一括確認")}</h2>{exactIds.length===0?<p className="mt-3 text-sm text-slate-600">{t(language,"No candidates meet the deterministic exact-match rule. Bulk confirmation is unavailable.","決定論的完全一致ルールを満たす候補はありません。一括確認は利用できません。")}</p>:<><p className="mt-3 text-sm">{t(language,"Every affected item is listed below. Bulk confirmation records Same canonical evidence item only for this exact set.","影響を受ける全項目を以下に表示します。一括確認では、この完全一致セットのみを「同一の正規エビデンス項目」として記録します。")}</p><ul className="mt-3 list-disc pl-5 text-sm">{report.candidates.filter(candidate=>exactIds.includes(migrationCandidateId(candidate))).map(candidate=><li key={migrationCandidateId(candidate)}>{candidate.left.legacyAlias} ↔ {candidate.right.legacyAlias}</li>)}</ul><label className="mt-4 flex items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" className="mt-0.5 h-5 w-5" checked={bulkConfirmed} onChange={event=>setBulkConfirmed(event.target.checked)}/>{t(language,"I explicitly confirm every exact candidate listed above.","上記の完全一致候補をすべて明示的に確認します。")}</label><button type="button" disabled={!bulkConfirmed} onClick={bulkSave} className="btn mt-4">{t(language,"Confirm listed exact matches","表示された完全一致を確認")}</button></>}{bulkMessage&&<p role="status" className="mt-3 rounded-lg bg-slate-100 p-3 text-sm font-semibold">{bulkMessage}</p>}</section>
  <div className="mt-8 space-y-10">{sources.map(sourceId=><section key={sourceId}><h2 className="text-2xl font-bold">{sourceId}</h2>{classes.map(classification=>{const candidates=report.candidates.filter(candidate=>candidate.sourceId===sourceId&&candidate.classification===classification);if(!candidates.length)return null;return <div key={classification} className="mt-6"><h3 className="text-lg font-bold">{label(classification)} <span className="text-slate-500">({candidates.length})</span></h3><div className="mt-3 space-y-5">{candidates.map(candidate=><CandidateCard key={migrationCandidateId(candidate)} candidate={candidate} saved={decisions.decisions[migrationCandidateId(candidate)]?.resolution} onSaved={setDecisions}/>)}</div></div>})}{!report.candidates.some(candidate=>candidate.sourceId===sourceId)&&<p className="mt-3 rounded-xl bg-slate-100 p-4 text-sm text-slate-600">{t(language,"No migration candidates identified for this source.","このソースには移行候補がありません。")}</p>}</section>)}</div></main>;
}
