"use client";
import Link from"next/link";import{useMemo,useState}from"react";import{useLanguage}from"./language-provider";import{t}from"@/lib/i18n";import{decisionIsValid,emptyDecision,itemReviewStatuses,outcomeReviewId,reviewProgress,type ContentReview,type ExtractedClaim,type ItemReviewDecision,type OutcomeData}from"@/lib/content-review-model";import type{PublicSourceRecord}from"@/lib/source-model";

function normalized(review:ContentReview){return{claims:Object.fromEntries(review.extracted_claims.map(claim=>[claim.claim_id,review.specialist_validation?.claims[claim.claim_id]??emptyDecision()])),outcomes:Object.fromEntries(review.outcome_data.map((_,index)=>{const id=outcomeReviewId(index);return[id,review.specialist_validation?.outcomes[id]??emptyDecision()]}))}}
export function ReviewDetailClient({review:initial,source}:{review:ContentReview;source:PublicSourceRecord}){const{language}=useLanguage();const[review,setReview]=useState(initial);const[validation,setValidation]=useState(()=>normalized(initial));const[saving,setSaving]=useState(false);const[message,setMessage]=useState<{tone:"error"|"success";text:string}|null>(null);const progress=useMemo(()=>reviewProgress({...review,specialist_validation:validation}),[review,validation]);
 function update(kind:"claims"|"outcomes",id:string,value:ItemReviewDecision){setValidation(current=>({...current,[kind]:{...current[kind],[id]:value}}));setMessage(null)}
 async function save(){setMessage(null);for(const claim of review.extracted_claims){const d=validation.claims[claim.claim_id];if(d.status==="Approved"&&!decisionIsValid(d,"claim",claim)){setMessage({tone:"error",text:t(language,`Cannot approve ${claim.claim_id}: reviewer name, valid date, original-source confirmation, supporting text, and source location are required.`,`${claim.claim_id} を承認できません：査読者名、有効な日付、原典確認、支持テキスト、出典箇所が必要です。`)});return}}for(const[outcomeIndex,outcome]of review.outcome_data.entries()){const id=outcomeReviewId(outcomeIndex),d=validation.outcomes[id];if(d.status==="Approved"&&!decisionIsValid(d,"outcome",outcome)){setMessage({tone:"error",text:t(language,`Cannot approve ${id}: reviewer name, valid date, original-source confirmation, and source location are required.`,`${id} を承認できません：査読者名、有効な日付、原典確認、出典箇所が必要です。`)});return}}
  setSaving(true);try{const response=await fetch(`/api/evaluation/2/reviews/${source.source_id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({specialist_validation:validation})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Save failed");const latestResponse=await fetch(`/api/evaluation/2/reviews/${source.source_id}`,{cache:"no-store"}),latest=await latestResponse.json();if(!latestResponse.ok)throw new Error(latest.error||"Reload failed");setReview(latest);setValidation(normalized(latest));setMessage({tone:"success",text:t(language,"Review decisions saved and reloaded from the review JSON.","レビュー判断を保存し、レビューJSONから再読み込みしました。")})}catch(error){setMessage({tone:"error",text:error instanceof Error?error.message:"Save failed"})}finally{setSaving(false)}}
 return <main className="shell py-12"><Link href="/evaluation/2/review" className="text-sm font-bold text-blue-700">← {t(language,"Question 2 Review Workspace","質問2レビューワークスペース")}</Link><div className="mt-7 eyebrow">{source.source_id}</div><h1 className="mt-3 max-w-4xl text-3xl font-semibold">{source.title}</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-600">{review.question}</p>
 <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[progress.total,t(language,"Total items","全項目")],[progress.completed,t(language,"Completed","完了")],[progress.incomplete,t(language,"Incomplete","未完了")],[progress.complete?t(language,"Complete","完了"):t(language,"Incomplete","未完了"),t(language,"Overall source-review status","ソースレビュー全体状況")]].map(([value,label])=><div className="card p-4" key={String(label)}><div className="text-2xl font-bold">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>)}</section>
 <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{t(language,"Validate against the original source. Do not enter patient-identifiable information.","原典と照合して検証してください。患者を特定できる情報は入力しないでください。")}</div>
 <section className="mt-8"><h2 className="text-xl font-bold">{t(language,"Claims","主張")}</h2><div className="mt-4 space-y-5">{review.extracted_claims.map(claim=><ReviewItem key={claim.claim_id} id={claim.claim_id} kind="claim" item={claim} decision={validation.claims[claim.claim_id]} language={language} update={value=>update("claims",claim.claim_id,value)}/>)}</div></section>
 <section className="mt-10"><h2 className="text-xl font-bold">{t(language,"Numeric outcomes","数値アウトカム")}</h2><div className="mt-4 space-y-5">{review.outcome_data.map((outcome,index)=>{const id=outcomeReviewId(index);return <ReviewItem key={id} id={id} kind="outcome" item={outcome} decision={validation.outcomes[id]} language={language} update={value=>update("outcomes",id,value)}/>})}</div></section>
 <div className="card mt-8 p-5"><button className="btn min-w-40" disabled={saving} onClick={save}>{saving?t(language,"Saving…","保存中…"):t(language,"Save review","レビューを保存")}</button>{message&&<p role="status" className={`mt-4 rounded-lg p-3 text-sm font-semibold ${message.tone==="success"?"bg-emerald-100 text-emerald-900":"bg-red-100 text-red-900"}`}>{message.text}</p>}</div></main>}

function ReviewItem({id,kind,item,decision,language,update}:{id:string;kind:"claim"|"outcome";item:ExtractedClaim|OutcomeData;decision:ItemReviewDecision;language:"en"|"ja";update:(value:ItemReviewDecision)=>void}){const claim=kind==="claim"?item as ExtractedClaim:null,outcome=kind==="outcome"?item as OutcomeData:null;const set=<K extends keyof ItemReviewDecision>(key:K,value:ItemReviewDecision[K])=>update({...decision,[key]:value});return <article className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold text-blue-700">{id}</div><h3 className="mt-2 font-bold leading-6">{claim?.claim_text??outcome?.outcome_name??"—"}</h3></div><span className="badge">{decision.status}</span></div>
 <dl className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-2">{claim&&<><Field label={t(language,"Supporting text","支持テキスト")} value={claim.exact_supporting_text}/><Field label={t(language,"Source location","出典箇所")} value={[claim.page,claim.section,claim.table,claim.figure,claim.source_location_note].filter(Boolean).join(" · ")}/></>}{outcome&&<><Field label={t(language,"Result","結果")} value={outcome.result_text}/><Field label={t(language,"Source location","出典箇所")} value={outcome.page_or_location}/></>}</dl>
 <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">{t(language,"Decision","判断")}<select className="source-control mt-2" value={decision.status} onChange={event=>set("status",event.target.value as ItemReviewDecision["status"])}>{itemReviewStatuses.map(status=><option key={status}>{status}</option>)}</select></label><label className="text-sm font-bold">{t(language,"Reviewer name","査読者名")}<input className="source-control mt-2" value={decision.reviewer_name} onChange={event=>set("reviewer_name",event.target.value)}/></label><label className="text-sm font-bold">{t(language,"Review date","レビュー日")}<input type="date" className="source-control mt-2" value={decision.review_date} onChange={event=>set("review_date",event.target.value)}/></label><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold"><input type="checkbox" className="h-5 w-5" checked={decision.original_source_confirmed} onChange={event=>set("original_source_confirmed",event.target.checked)}/>{t(language,"Original source confirmed","原典確認済み")}</label><label className="text-sm font-bold md:col-span-2">{t(language,"Reviewer note","査読者注記")}<textarea className="source-control mt-2 min-h-24 resize-y" value={decision.reviewer_note} onChange={event=>set("reviewer_note",event.target.value)}/></label></div></article>}
function Field({label,value}:{label:string;value:string|null|undefined}){return <div><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap leading-6">{value?.trim()||"—"}</dd></div>}
