"use client";
import Link from"next/link";
import{useState,type FormEvent}from"react";
import{useLanguage}from"./language-provider";
import{t}from"@/lib/i18n";
import type{SynthesisDraft,SynthesisReview}from"@/lib/synthesis-drafts";
import{synthesisDisplayStatus,type SelectedSynthesisDecision}from"@/lib/synthesis-validation";

type Row={sourceId:string;title:string;complete:boolean;incomplete:number};
const empty:SynthesisReview={decision:"Pending",reviewer_name:"",review_date:"",confirmed:false,reviewer_note:""};
const selectedFromReview=(review:SynthesisReview):SelectedSynthesisDecision=>review.decision==="Approve synthesis"?"Approved":review.decision==="Return for correction"?"Requires correction":null;
const validDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return!Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value};

export function SynthesisClient({draft:initial,rows}:{draft:SynthesisDraft;rows:Row[]}){
 const{language}=useLanguage(),initialReview=initial.synthesis_review??empty;
 const[draft,setDraft]=useState(initial),[review,setReview]=useState(initialReview);
 const[selectedDecision,setSelectedDecision]=useState<SelectedSynthesisDecision>(()=>selectedFromReview(initialReview));
 const[saving,setSaving]=useState(false),[message,setMessage]=useState<{tone:"success"|"warning"|"error";text:string;reviewer?:string;date?:string}|null>(null);
 const ready=rows.length===3&&rows.every(row=>row.complete),incompleteRows=rows.filter(row=>!row.complete),savedStatus=synthesisDisplayStatus(review.decision,ready);

 async function save(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setMessage(null);
  if(!selectedDecision||!review.reviewer_name.trim()||!validDate(review.review_date)||!review.confirmed||(selectedDecision==="Requires correction"&&!review.reviewer_note.trim())){setMessage({tone:"error",text:t(language,"Select a decision and complete all required synthesis fields.","判断を選択し、統合結果の必須項目をすべて入力してください。")});return}
  const submittedReview:SynthesisReview={...review,decision:selectedDecision==="Approved"?"Approve synthesis":"Return for correction"};setSaving(true);
  try{const response=await fetch("/api/evaluation/2/synthesis",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({review:submittedReview})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Save failed");const latestResponse=await fetch("/api/evaluation/2/synthesis",{cache:"no-store"}),latest=await latestResponse.json();if(!latestResponse.ok)throw new Error(latest.error||"Reload failed");const latestReview:SynthesisReview=latest.synthesis_review??empty;setDraft(latest);setReview(latestReview);setSelectedDecision(selectedFromReview(latestReview));setMessage({tone:selectedDecision==="Approved"&&!ready?"warning":"success",text:selectedDecision==="Approved"?t(language,"Synthesis Approved ✓","統合結果を承認済み ✓"):t(language,"Returned for correction","修正のため差し戻しました"),reviewer:latestReview.reviewer_name,date:latestReview.review_date})}catch(error){setMessage({tone:"error",text:error instanceof Error?error.message:"Save failed"})}finally{setSaving(false)}
 }

 return <main className="shell py-12"><Link className="text-sm font-bold text-blue-700" href="/evaluation/2/review">← {t(language,"Question 2 Review Workspace","質問2レビューワークスペース")}</Link><div className="mt-7 eyebrow">{t(language,"Synthesis validation","統合検証")}</div><h1 className="mt-3 max-w-4xl text-3xl font-semibold">{t(language,"Evaluation Question 2 Synthesis","評価質問2 統合")}</h1><p className="mt-4 max-w-4xl text-lg leading-8">{draft.question}</p>
 {review.decision==="Approve synthesis"&&<div className={`mt-6 rounded-xl border p-4 ${ready?"border-emerald-300 bg-emerald-50 text-emerald-900":"border-amber-300 bg-amber-50 text-amber-950"}`}><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${ready?"bg-emerald-600 text-white":"bg-amber-500 text-white"}`}>{savedStatus==="Specialist validated"?t(language,"Specialist validated","専門医検証済み"):t(language,"Approved with unresolved Evidence","未完了のエビデンスを含む承認")}</span>{!ready&&<p className="mt-3 text-sm font-semibold">{t(language,"This synthesis was approved before all Evidence reviews were completed.","すべてのエビデンスレビューが完了する前に、この統合結果は承認されました。")}</p>}</div>}
 <section className="card mt-7 overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">{t(language,"Evidence review warnings","エビデンスレビューの警告")}</h2><p className="mt-2 text-sm text-slate-600">{t(language,"These items are incomplete, but they do not prevent saving a synthesis decision.","未完了の項目がありますが、統合結果の承認保存を妨げるものではありません。")}</p></div><div className="divide-y divide-slate-200">{rows.map(row=><div className="grid gap-2 p-5 md:grid-cols-[9rem_minmax(0,1fr)_8rem_7rem_9rem] md:items-center" key={row.sourceId}><b>{row.sourceId}</b><span>{row.title}</span><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${row.complete?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{row.complete?t(language,"Complete","完了"):t(language,"Incomplete","未完了")}</span><span className="text-sm">{row.incomplete} {t(language,"incomplete","未完了")}</span><Link className="font-bold text-blue-700" href={`/evaluation/2/review/${row.sourceId}`}>{t(language,"Review source","ソースをレビュー")}</Link></div>)}</div></section>
 <form className="card mt-7 p-6" onSubmit={save}><h2 className="text-xl font-bold">{t(language,"Synthesis decision","統合判断")}</h2><fieldset className="mt-5"><legend className="font-bold">{t(language,"Decision","判断")}</legend><div className="mt-3 space-y-3"><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 p-3 font-semibold"><input type="radio" name="decision" value="Approved" required checked={selectedDecision==="Approved"} onChange={event=>setSelectedDecision(event.target.value as"Approved")}/>{t(language,"Approve synthesis","統合を承認")}</label><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 p-3 font-semibold"><input type="radio" name="decision" value="Requires correction" required checked={selectedDecision==="Requires correction"} onChange={event=>setSelectedDecision(event.target.value as"Requires correction")}/>{t(language,"Return for correction","修正のため差し戻す")}</label></div></fieldset>
 {!ready&&<div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-950"><p>{t(language,"These items are incomplete, but they do not prevent saving a synthesis decision.","未完了の項目がありますが、統合結果の承認保存を妨げるものではありません。")}</p><ul className="mt-3 space-y-2">{incompleteRows.map(row=><li key={row.sourceId}><Link className="font-bold text-blue-700" href={`/evaluation/2/review/${row.sourceId}`}>{row.sourceId}: {t(language,"Review source","ソースをレビュー")}</Link></li>)}</ul></div>}
 <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">{t(language,"Reviewer name","査読者名")}<input required className="source-control mt-2" value={review.reviewer_name} onChange={event=>setReview({...review,reviewer_name:event.target.value})}/></label><label className="text-sm font-bold">{t(language,"Review date","レビュー日")}<input required type="date" className="source-control mt-2" value={review.review_date} onChange={event=>setReview({...review,review_date:event.target.value})}/></label><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold md:col-span-2"><input required type="checkbox" className="h-5 w-5" checked={review.confirmed} onChange={event=>setReview({...review,confirmed:event.target.checked})}/>{t(language,"I confirm that I reviewed the synthesis.","統合結果をレビューしたことを確認します。")}</label><label className="text-sm font-bold md:col-span-2">{t(language,selectedDecision==="Requires correction"?"Reviewer note (required)":"Reviewer note",selectedDecision==="Requires correction"?"査読者注記（必須）":"査読者注記")}<textarea required={selectedDecision==="Requires correction"} className="source-control mt-2 min-h-24 resize-y" value={review.reviewer_note} onChange={event=>setReview({...review,reviewer_note:event.target.value})}/></label></div>
 <div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><h3 className="font-bold">{t(language,"Diagnostic summary","診断概要")}</h3><dl className="mt-3 grid gap-2 sm:grid-cols-[14rem_1fr]"><dt className="font-semibold">{t(language,"Selected decision","選択した判断")}</dt><dd>{selectedDecision??t(language,"None","なし")}</dd><dt className="font-semibold">{t(language,"Reviewer entered","査読者入力済み")}</dt><dd>{review.reviewer_name.trim()?t(language,"Yes","はい"):t(language,"No","いいえ")}</dd><dt className="font-semibold">{t(language,"Review date entered","レビュー日入力済み")}</dt><dd>{review.review_date?t(language,"Yes","はい"):t(language,"No","いいえ")}</dd><dt className="font-semibold">{t(language,"Confirmation checked","確認チェック済み")}</dt><dd>{review.confirmed?t(language,"Yes","はい"):t(language,"No","いいえ")}</dd></dl></div>
 <button type="submit" className="btn mt-5">{saving?t(language,"Saving…","保存中…"):t(language,"Save synthesis decision","統合結果の判断を保存")}</button>{message&&<div role="status" className={`mt-4 rounded-lg p-4 font-bold ${message.tone==="success"?"bg-emerald-100 text-emerald-900":message.tone==="warning"?"bg-amber-100 text-amber-950":"bg-red-100 text-red-900"}`}><p>{message.text}</p>{message.reviewer&&message.date&&<p className="mt-2 text-sm">{t(language,"Reviewer","査読者")}: {message.reviewer} · {t(language,"Review date","レビュー日")}: {message.date}</p>}</div>}</form></main>
}
