import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { newCanonicalId } from "../lib/authoring/ids.ts";
import { parseCanonicalId } from "../lib/canonical-evidence/identifiers.ts";
const prefixes={source:"SRC_",sourceVersion:"SRV_",sourceFile:"SFL_",evidence:"EVI_",review:"REV_",location:"LOC_",reviewer:"RVR_",referenceChain:"RFC_"}as const;
for(const kind of Object.keys(prefixes)as Array<keyof typeof prefixes>)assert.doesNotThrow(()=>parseCanonicalId(newCanonicalId(kind),prefixes[kind]));
const sql=await readFile("supabase/migrations/202607180001_minimum_authoring_portal.sql","utf8");
assert.match(sql,/values\('aes-private-sources','aes-private-sources',false/);assert.match(sql,/enable row level security/g);assert.match(sql,/authenticated insert reviews/);assert.match(sql,/decision <> 'approved' or original_source_confirmed/);assert.match(sql,/predecessor_ref/);assert.match(sql,/Synthetic Polymer Durability Report/);assert.doesNotMatch(sql,/source_documents\/private/);
const grantsSql=await readFile("supabase/migrations/202607180002_authenticated_authoring_grants.sql","utf8");
assert.match(grantsSql,/grant usage on schema public to authenticated/);
for(const table of ["authoring_sources","authoring_source_versions","authoring_source_files","authoring_evidence_revisions"])assert.match(grantsSql,new RegExp(`public\\.${table}`));
assert.match(grantsSql,/grant select, insert, update on table/);
for(const table of ["authoring_specialist_reviews","authoring_audit_events"])assert.match(grantsSql,new RegExp(`public\\.${table}`));
assert.match(grantsSql,/grant select, insert on table/);
assert.doesNotMatch(grantsSql,/create policy|drop policy|storage\.|service_role/i);
const pdfSql=await readFile("supabase/migrations/202607180003_pdf_evidence_authoring.sql","utf8");
assert.match(pdfSql,/create table public\.authoring_pdf_pages/);assert.match(pdfSql,/enable row level security/);assert.match(pdfSql,/authenticated read extracted PDF pages/);assert.match(pdfSql,/source_text_sha256/);assert.match(pdfSql,/quotation_sha256/);assert.match(pdfSql,/authoring_method in \('manual','ai_suggested'\)/);assert.match(pdfSql,/quotation_location_verified/);assert.doesNotMatch(pdfSql,/public\s*=\s*true|service_role/i);
const repository=await readFile("lib/authoring/repository.ts","utf8"),detail=await readFile("app/authoring/(portal)/sources/[sourceId]/page.tsx","utf8"),layout=await readFile("app/authoring/(portal)/layout.tsx","utf8");
assert.match(repository,/original_source_confirmed/);assert.match(repository,/revision_number\+1/);assert.match(repository,/upsert:false/);assert.doesNotMatch(repository,/getPublicUrl/);assert.doesNotMatch(detail,/Approve All/);assert.match(layout,/requireAuthoringUser/);
assert.match(repository,/extractNativePdfText/);assert.match(repository,/Quotation is not present on the selected extracted PDF page/);assert.match(repository,/Specialist must verify the quotation and location/);assert.match(repository,/review_lifecycle:"pending"/);assert.match(repository,/quotationSha256/);
const viewer=await readFile("app/authoring/files/[sourceFileId]/route.ts","utf8"),candidateRoute=await readFile("app/api/authoring/sources/[sourceId]/ai-candidates/route.ts","utf8"),provider=await readFile("lib/authoring/ai-provider.ts","utf8"),workspace=await readFile("components/authoring-pdf-workspace.tsx","utf8");
assert.match(viewer,/downloadPrivateSourceFile/);assert.match(viewer,/cache-control":"private, no-store/);assert.doesNotMatch(viewer,/object_path|source_documents/);
assert.match(candidateRoute,/requireAuthoringUser/);assert.match(candidateRoute,/AI setup required/);assert.match(candidateRoute,/\.eq\("source_id",sourceId\)/);
assert.match(provider,/input\.pageText\.includes\(quote\)/);assert.match(provider,/neverApprove:true/);assert.match(provider,/primary_source_not_yet_verified/);
assert.match(workspace,/side|PDF-to-evidence workspace/);assert.match(workspace,/quotation_location_verified/);assert.match(workspace,/AI suggested ≠ reviewer verified ≠ original source verified/);assert.match(workspace,/Save Pending evidence revision/);
const login=await readFile("app/authoring/login/page.tsx","utf8");assert.match(login,/Setup required/);assert.match(login,/患者を特定できる情報/);
console.log("Authoring Portal tests: 56 passed");
