import assert from "node:assert/strict";
import type { ContentReview, ExtractedClaim, OutcomeData } from "../lib/content-review-model.ts";
import { finalizationPreflight, loadReviewWorkflowContext, parseGitPorcelain, requireExistingReview, requireQuestionAndSourceIds, unrelatedGitChanges } from "../lib/review-workflow.ts";
const root = process.cwd(), context = await loadReviewWorkflowContext(root, "Q02", "AES-REG-001");
requireExistingReview(context); assert.equal(context.sourceId, "AES-REG-001"); assert.equal(context.questionId, "Q02");
const q03 = await loadReviewWorkflowContext(root, "Q03", "AES-GDL-001"); assert.equal(q03.review, null, "Q03 cannot reuse a Q02 review file");
await assert.rejects(() => loadReviewWorkflowContext(root, "Q99", "AES-REG-001"), /Unknown or unsupported question/);
await assert.rejects(() => loadReviewWorkflowContext(root, "Q02", "AES-REG-999"), /Unknown or unsupported source/);
for (const unsafe of ["../AES-REG-001", "AES-REG-001/../../etc", "AES-REG-001%2F..%2F.."]) assert.throws(() => requireQuestionAndSourceIds(["Q02", unsafe]), /Unsafe or invalid/);
for (const unsafe of ["../Q02", "Q02/../../etc", "Q02%2F..%2F.."]) assert.throws(() => requireQuestionAndSourceIds([unsafe, "AES-REG-001"]), /Unsafe or invalid/);
const claim: ExtractedClaim = { claim_id: "TEST-C01", claim_text: "Test", evidence_category: "Test", exact_supporting_text: "Support", page: "1", section: null, table: null, figure: null, source_location_note: null, direct_or_indirect: "Direct", confidence: "High", verified_by_reviewer: false, suitable_for_generated_answer: false };
const outcome: OutcomeData = { outcome_id: "TEST-O01", outcome_name: "Outcome", population: "Population", intervention: "Intervention", comparator: null, follow_up: "1 year", result_text: "Result", numeric_result: "1", page_or_location: "p. 1", verified_by_reviewer: false };
const review: ContentReview = { review_id: "TEST", evaluation_question_number: 2, question: "Question", source_id: "AES-REG-001", review_status: "In review", reviewer: null, review_date: null, source_access_type: null, source_version_or_date: null, relevant_sections: [], extracted_claims: [claim], guideline_recommendations: [], outcome_data: [outcome], limitations: [], contradictions: [], reviewer_notes: null, last_updated: "2026-07-15", specialist_validation: { claims: { "TEST-C01": { status: "Pending", reviewer_name: "", review_date: "", original_source_confirmed: false, reviewer_note: "" } }, outcomes: { "outcome-1": { status: "Pending", reviewer_name: "", review_date: "", original_source_confirmed: false, reviewer_note: "" } } } };
const expected = "database/content_reviews/Q02_AES-REG-001.json", cleanChange = parseGitPorcelain(` M ${expected}\n`);
assert.equal(finalizationPreflight(review, cleanChange, expected).ok, false);
assert.deepEqual(unrelatedGitChanges(parseGitPorcelain(` M ${expected}\n?? notes.txt\n`), expected).map(change => change.path), ["notes.txt"]);
const complete: ContentReview = structuredClone(review); complete.specialist_validation!.claims["TEST-C01"] = { status: "Approved", reviewer_name: "Specialist", review_date: "2026-07-15", original_source_confirmed: true, reviewer_note: "" }; complete.specialist_validation!.outcomes["outcome-1"] = { status: "Excluded", reviewer_name: "Specialist", review_date: "2026-07-15", original_source_confirmed: true, reviewer_note: "Not applicable" };
assert.equal(finalizationPreflight(complete, cleanChange, expected).ok, true); assert.equal(finalizationPreflight(complete, parseGitPorcelain(` M ${expected}\n?? notes.txt\n`), expected).ok, false); complete.extracted_claims[0].suitable_for_generated_answer = true; assert.equal(finalizationPreflight(complete, cleanChange, expected).ok, false);
console.log("Review workflow tests: 18 passed");
