import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import type { DuplicateCandidate } from "../lib/canonical-evidence/duplicate-candidates.ts";
import type { MigrationCandidateReport, MigrationDecisionFile } from "../lib/migration-review-model.ts";
import { applyExactBulkDecision, applyIndividualDecision, exactCandidateIds, isDeterministicallyExact, migrationCandidateId } from "../lib/migration-review-model.ts";

const report = JSON.parse(await readFile("migration_reports/q02-q03-canonical-candidates/candidate-report.json", "utf8")) as MigrationCandidateReport;
const decisionFile = JSON.parse(await readFile("migration_reports/q02-q03-canonical-candidates/migration-decisions.json", "utf8")) as MigrationDecisionFile;
assert.equal(report.candidates.length, 27, "all report candidates available to the page");
assert.deepEqual(report.sourceComparisons.map(item => item.sourceId), ["AES-GDL-001", "AES-GDL-002", "AES-GDL-003", "AES-GDL-004", "AES-RCT-003"]);
assert(report.candidates.every(candidate => candidate.requiresManualResolution && !candidate.merged), "every candidate remains manual and unmerged");
assert(report.candidates.every(candidate => ["wording", "quotation", "location", "interpretation", "limitation", "reviewer", "review_date", "decision", "verification_status"].every(field => candidate.comparisons.some(comparison => comparison.field === field))), "all side-by-side fields exist");
assert.equal(exactCandidateIds(report).length, 0, "current report has no deterministic exact candidates");
const first = report.candidates[0], firstId = migrationCandidateId(first), now = "2099-01-01T00:00:00.000Z";
const individual = applyIndividualDecision(decisionFile, report, firstId, "needs_further_review", now);
assert.equal(individual.decisions[firstId].resolution, "needs_further_review"); assert.equal(individual.canonicalRecordsCreated, false); assert.equal(individual.canonicalApprovalsCreated, false); assert.equal(individual.automaticMergePerformed, false);
assert.throws(() => applyIndividualDecision(decisionFile, report, "unknown", "needs_further_review", now), /Unknown migration candidate/);
const exact = structuredClone(first) as DuplicateCandidate; exact.comparisons = exact.comparisons.map(comparison => ["wording", "quotation", "location", "interpretation", "limitation"].includes(comparison.field) ? { ...comparison, right: comparison.left, equal: true } : comparison);
assert.equal(isDeterministicallyExact(exact), true);
const exactReport = { ...report, candidates: [exact] }, exactId = migrationCandidateId(exact);
assert.throws(() => applyExactBulkDecision(decisionFile, exactReport, [exactId], false, now), /Explicit bulk confirmation/);
assert.throws(() => applyExactBulkDecision(decisionFile, exactReport, ["unknown"], true, now), /every and only/);
const bulk = applyExactBulkDecision(decisionFile, exactReport, [exactId], true, now);
assert.equal(bulk.decisions[exactId].resolution, "same_canonical_evidence_item"); assert.equal(bulk.automaticMergePerformed, false);
const reviewFiles = report.sourceComparisons.flatMap(source => [`database/content_reviews/Q02_${source.sourceId}.json`, `database/content_reviews/Q03_${source.sourceId}.json`]);
const before = await Promise.all(reviewFiles.map(async file => createHash("sha256").update(await readFile(file)).digest("hex")));
applyIndividualDecision(decisionFile, report, firstId, "keep_separate_evidence_items", now);
const after = await Promise.all(reviewFiles.map(async file => createHash("sha256").update(await readFile(file)).digest("hex")));
assert.deepEqual(after, before, "migration decisions do not mutate Q02/Q03 reviews");
const component = await readFile("components/migration-review-client.tsx", "utf8");
assert.match(component, /Same canonical evidence item/); assert.match(component, /Keep as separate evidence items/); assert.match(component, /Needs further review/); assert.doesNotMatch(component, /Approve All/);
console.log("Migration review tests: 16 passed");
