import {readFile} from "node:fs/promises";import path from "node:path";import {parseCsv} from "../lib/source-csv.ts";
type SchemaProperty={enum?:unknown[];pattern?:string};type Schema={required:string[];properties:Record<string,SchemaProperty>};
const root=process.cwd();const[csvText,schemaText]=await Promise.all([readFile(path.join(root,"database/source_catalog.csv"),"utf8"),readFile(path.join(root,"database/source_schema.json"),"utf8")]);const schema=JSON.parse(schemaText) as Schema;const records=parseCsv(csvText);const errors:string[]=[];const warnings:string[]=[];const ids=new Map<string,number>();
const issue=(list:string[],row:number,field:string,message:string)=>list.push(`Row ${row}, ${field}: ${message}`);const validDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return !Number.isNaN(date.valueOf())&&date.toISOString().slice(0,10)===value};
records.forEach((record,index)=>{const row=index+2;for(const field of schema.required){if(!Object.hasOwn(record,field))issue(errors,row,field,"required column is missing")}for(const field of ["source_id","title","source_type","region","language","verification_status"]){if(!record[field]?.trim())issue(errors,row,field,"required value is blank")}if(record.source_id){const previous=ids.get(record.source_id);if(previous)issue(errors,row,"source_id",`duplicate of row ${previous}`);else ids.set(record.source_id,row);const pattern=schema.properties.source_id.pattern;if(pattern&&!new RegExp(pattern).test(record.source_id))issue(errors,row,"source_id","does not match the required AES identifier format")}
  for(const field of ["publication_date","approval_date","last_verified_date"]){if(record[field]&&!validDate(record[field]))issue(errors,row,field,"must be a valid ISO date (YYYY-MM-DD)")}
  for(const[field,property]of Object.entries(schema.properties)){const allowed=property.enum?.filter(value=>value!==null).map(String);if(allowed&&record[field]&&!allowed.includes(record[field]))issue(errors,row,field,`must be one of: ${allowed.join("; ")}`)}
  if(record.publication_year&&(!/^\d{4}$/.test(record.publication_year)||Number(record.publication_year)<1800))issue(errors,row,"publication_year","must be a four-digit year of 1800 or later");if(record.PMID&&!/^\d+$/.test(record.PMID))issue(errors,row,"PMID","must contain digits only");if(record.relevant_evaluation_questions){for(const value of record.relevant_evaluation_questions.split(";").map(v=>v.trim()).filter(Boolean)){if(!/^\d+$/.test(value)||Number(value)<1||Number(value)>30)issue(errors,row,"relevant_evaluation_questions",`"${value}" must be an integer from 1 to 30`)}}
  if(record.local_file_path&&/(patient|mrn|medical[-_ ]?record|dob|date[-_ ]?of[-_ ]?birth|ssn|姓名|患者|診療録|生年月日)/i.test(record.local_file_path))issue(warnings,row,"local_file_path","contains a term that may indicate patient-identifiable information; review before storage")
});
console.log("Source catalog validation");console.log(`Total records: ${records.length}`);console.log(`Valid records: ${records.length-new Set(errors.map(error=>error.match(/^Row (\d+)/)?.[1]).filter(Boolean)).size}`);console.log(`Warning count: ${warnings.length}`);console.log(`Error count: ${errors.length}`);for(const warning of warnings)console.warn(`WARNING: ${warning}`);for(const error of errors)console.error(`ERROR: ${error}`);if(errors.length)process.exitCode=1;
