import "server-only";
import{authoringAiSetup}from"./config";
export interface CandidateSuggestion{exactQuotation:string;pdfPage:number;printedPage:string;sectionOrRecommendation:string;textAnchor:string;tableLocation:string;figureLocation:string;interpretation:string;limitation:string;authorityType:string;verificationStatus:"primary_source_not_yet_verified"}
export interface CandidateRequest{pageText:string;selectedText:string;pdfPage:number;sourceTitle:string;sourceLanguage:string}
export interface EvidenceCandidateProvider{suggest(input:CandidateRequest):Promise<CandidateSuggestion[]>}
const clean=(value:unknown)=>typeof value==="string"?value.trim():"";
class HttpEvidenceCandidateProvider implements EvidenceCandidateProvider{
  async suggest(input:CandidateRequest){const config=authoringAiSetup(),response=await fetch(config.endpoint,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${config.apiKey}`},body:JSON.stringify({model:config.model,task:"evidence_candidate_suggestion",constraints:{neverApprove:true,quotationMustBeVerbatim:true,pdfPageMustEqual:input.pdfPage},source:input})});if(!response.ok)throw new Error("AI candidate service failed");const payload=await response.json()as{candidates?:unknown[]};return(payload.candidates??[]).flatMap(raw=>{if(!raw||typeof raw!=="object")return[];const item=raw as Record<string,unknown>,quote=clean(item.exactQuotation);if(!quote||!input.pageText.includes(quote)||(input.selectedText&&!input.selectedText.includes(quote)&&!quote.includes(input.selectedText)))return[];const safeLocation=(value:unknown)=>{const v=clean(value);return v&&input.pageText.includes(v)?v:""};return[{exactQuotation:quote,pdfPage:input.pdfPage,printedPage:safeLocation(item.printedPage),sectionOrRecommendation:safeLocation(item.sectionOrRecommendation),textAnchor:safeLocation(item.textAnchor)||quote.slice(0,120),tableLocation:safeLocation(item.tableLocation),figureLocation:safeLocation(item.figureLocation),interpretation:clean(item.interpretation),limitation:clean(item.limitation),authorityType:clean(item.authorityType)||"expert_interpretation",verificationStatus:"primary_source_not_yet_verified" as const}]})}
}
export function evidenceCandidateProvider():EvidenceCandidateProvider|null{return authoringAiSetup().configured?new HttpEvidenceCandidateProvider():null}
