import"server-only";
import{createHash}from"node:crypto";
import{authoringSetup}from"./config";
import{newCanonicalId}from"./ids";
import{extractNativePdfText}from"./pdf-extraction";
import{validateFinalizedPdf,validatePdfUploadRequest}from"./pdf-upload-validation";
import{requireAuthoringUser}from"./supabase-server";
const MAX_PAGE_CHARS=100_000;
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message)};
const validFileId=(value:string)=>/^SFL_[0-9a-f-]{36}$/.test(value);
async function audit(client:Awaited<ReturnType<typeof requireAuthoringUser>>["client"],actor:string,sourceId:string,action:string,entityType:string,entityId:string,details:Record<string,unknown>={}){fail((await client.from("authoring_audit_events").insert({source_id:sourceId,action,entity_type:entityType,entity_id:entityId,actor_id:actor,details})).error)}
export async function createSignedPdfUpload(input:{sourceId:string;sourceVersionId:string;byteLength:number;sha256:string;mimeType:string}){const{client,user}=await requireAuthoringUser();if(!/^SRC_[0-9a-f-]{36}$/.test(input.sourceId)||!/^SRV_[0-9a-f-]{36}$/.test(input.sourceVersionId))throw new Error("Unsupported source identity");validatePdfUploadRequest(input);const{data:version,error}=await client.from("authoring_source_versions").select("source_version_id").eq("source_version_id",input.sourceVersionId).eq("source_id",input.sourceId).maybeSingle();fail(error);if(!version)throw new Error("Unauthorized source version");const sourceFileId=newCanonicalId("sourceFile"),objectPath=`${user.id}/${sourceFileId}.pdf`,{data,error:signedError}=await client.storage.from(authoringSetup().bucket).createSignedUploadUrl(objectPath,{upsert:false});fail(signedError);if(!data?.signedUrl)throw new Error("Unable to create signed upload");const expiresAt=new Date(Date.now()+10*60_000).toISOString(),{data:session,error:sessionError}=await client.from("authoring_upload_sessions").insert({source_file_id:sourceFileId,source_id:input.sourceId,source_version_id:input.sourceVersionId,object_path:objectPath,expected_sha256:input.sha256,expected_byte_length:input.byteLength,expected_mime_type:input.mimeType,created_by:user.id,expires_at:expiresAt}).select("upload_id").single();fail(sessionError);if(!session)throw new Error("Unable to record upload session");return{uploadId:session.upload_id,sourceFileId,signedUrl:data.signedUrl,expiresAt}}
export async function finalizeSignedPdfUpload(uploadId:string){const{client,user}=await requireAuthoringUser();if(!/^[0-9a-f-]{36}$/.test(uploadId))throw new Error("Invalid upload ID");const{data:session,error}=await client.from("authoring_upload_sessions").select("upload_id,source_file_id,source_id,source_version_id,object_path,expected_sha256,expected_byte_length,expected_mime_type,expires_at,finalized_at,created_by").eq("upload_id",uploadId).eq("created_by",user.id).maybeSingle();fail(error);if(!session||session.finalized_at||new Date(session.expires_at).getTime()<Date.now())throw new Error("Upload session is unavailable or expired");const{data:blob,error:downloadError}=await client.storage.from(authoringSetup().bucket).download(session.object_path);fail(downloadError);if(!blob)throw new Error("Uploaded object not found");const bytes=Buffer.from(await blob.arrayBuffer()),hash=createHash("sha256").update(bytes).digest("hex");validateFinalizedPdf({expectedByteLength:session.expected_byte_length,actualByteLength:bytes.length,expectedSha256:session.expected_sha256,actualSha256:hash,expectedMimeType:session.expected_mime_type,actualMimeType:blob.type,signature:bytes.subarray(0,5).toString()});fail((await client.from("authoring_source_files").insert({source_file_id:session.source_file_id,source_version_id:session.source_version_id,source_id:session.source_id,object_path:session.object_path,sha256:hash,byte_length:bytes.length,created_by:user.id,extraction_status:"pending"})).error);fail((await client.from("authoring_upload_sessions").update({finalized_at:new Date().toISOString()}).eq("upload_id",uploadId).eq("created_by",user.id)).error);await audit(client,user.id,session.source_id,"source_file.uploaded","source_file",session.source_file_id,{sourceVersionId:session.source_version_id,sha256:hash,byteLength:bytes.length,directUpload:true});return{sourceFileId:session.source_file_id,status:"pending" as const}}
export async function extractSourceFile(sourceFileId:string){const{client,user}=await requireAuthoringUser();if(!validFileId(sourceFileId))throw new Error("Unsupported source file ID");const{data:file,error}=await client.from("authoring_source_files").select("source_file_id,source_id,object_path,sha256,byte_length,created_by").eq("source_file_id",sourceFileId).eq("created_by",user.id).maybeSingle();fail(error);if(!file)throw new Error("Unauthorized source file");fail((await client.from("authoring_source_files").update({extraction_status:"extracting",extraction_error:null}).eq("source_file_id",sourceFileId).eq("created_by",user.id)).error);try{const{data:blob,error:downloadError}=await client.storage.from(authoringSetup().bucket).download(file.object_path);fail(downloadError);if(!blob)throw new Error("Private PDF unavailable");const bytes=new Uint8Array(await blob.arrayBuffer());if(bytes.byteLength!==file.byte_length||createHash("sha256").update(bytes).digest("hex")!==file.sha256||Buffer.from(bytes.subarray(0,5)).toString()!=="%PDF-")throw new Error("Private PDF integrity verification failed");const pages=await extractNativePdfText(bytes);fail((await client.from("authoring_pdf_pages").delete().eq("source_file_id",sourceFileId)).error);for(let index=0;index<pages.length;index+=10)fail((await client.from("authoring_pdf_pages").insert(pages.slice(index,index+10).map(page=>({source_file_id:sourceFileId,pdf_page:page.pdfPage,extracted_text:page.text,text_sha256:page.textSha256})))).error);const textPageCount=pages.filter(page=>page.text.length>0).length;fail((await client.from("authoring_source_files").update({extraction_status:"complete",page_count:pages.length,text_page_count:textPageCount,extraction_error:null}).eq("source_file_id",sourceFileId).eq("created_by",user.id)).error);await audit(client,user.id,file.source_id,"source_file.extracted","source_file",sourceFileId,{pageCount:pages.length,textPageCount});return{status:"complete" as const,pageCount:pages.length,textPageCount}}catch(error){const message=error instanceof Error?error.message.slice(0,500):"Extraction failed";await client.from("authoring_source_files").update({extraction_status:"failed",extraction_error:message}).eq("source_file_id",sourceFileId).eq("created_by",user.id);await audit(client,user.id,file.source_id,"source_file.extraction_failed","source_file",sourceFileId,{error:message});throw new Error(message)}}
export async function getExtractedPage(sourceFileId:string,pdfPage:number,offset:number){const{client,user}=await requireAuthoringUser();if(!validFileId(sourceFileId)||!Number.isInteger(pdfPage)||pdfPage<1||!Number.isInteger(offset)||offset<0)throw new Error("Invalid page request");const{data:file,error:fileError}=await client.from("authoring_source_files").select("source_file_id,page_count,extraction_status").eq("source_file_id",sourceFileId).eq("created_by",user.id).maybeSingle();fail(fileError);if(!file)throw new Error("Unauthorized source file");const{data:page,error}=await client.from("authoring_pdf_pages").select("pdf_page,extracted_text,text_sha256").eq("source_file_id",sourceFileId).eq("pdf_page",pdfPage).maybeSingle();fail(error);if(!page)throw new Error("Extracted page not found");const totalCharacters=page.extracted_text.length,text=page.extracted_text.slice(offset,offset+MAX_PAGE_CHARS);return{sourceFileId,pdfPage:page.pdf_page,text,textSha256:page.text_sha256,offset,nextOffset:offset+text.length,totalCharacters,hasMore:offset+text.length<totalCharacters,pageCount:file.page_count,extractionStatus:file.extraction_status}}
