import "server-only";
import{createHash}from"node:crypto";
import{authoringSetup}from"./config";
import{newCanonicalId}from"./ids";
import{requireAuthoringUser}from"./supabase-server";
import type{SourceBundle}from"./model";
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message)};
async function audit(client:Awaited<ReturnType<typeof requireAuthoringUser>>["client"],actor:string,action:string,type:string,id:string,details:Record<string,unknown>={}){const sourceId=type==="source"?id:typeof details.sourceId==="string"?details.sourceId:null;fail((await client.from("authoring_audit_events").insert({source_id:sourceId,action,entity_type:type,entity_id:id,actor_id:actor,details})).error)}
export async function listAuthoringSources(){const{client}=await requireAuthoringUser(),{data,error}=await client.from("authoring_sources").select("*").order("created_at",{ascending:false});fail(error);return data??[]}
export async function getSourceBundle(sourceId:string):Promise<SourceBundle|null>{const{client}=await requireAuthoringUser();const{data:source,error}=await client.from("authoring_sources").select("*").eq("source_id",sourceId).maybeSingle();fail(error);if(!source)return null;const[{data:versions,error:ve},{data:revisions,error:re},{data:reviews,error:rve},{data:auditRows,error:ae}]=await Promise.all([client.from("authoring_source_versions").select("*").eq("source_id",sourceId).order("created_at"),client.from("authoring_evidence_revisions").select("*").eq("source_id",sourceId).order("created_at"),client.from("authoring_specialist_reviews").select("*").eq("source_id",sourceId).order("created_at"),client.from("authoring_audit_events").select("*").eq("source_id",sourceId).order("created_at",{ascending:false})]);[ve,re,rve,ae].forEach(fail);return{source,versions:versions??[],revisions:revisions??[],reviews:reviews??[],audit:auditRows??[]}}
export async function createSourceRecord(form:FormData){const{client,user}=await requireAuthoringUser();const title=String(form.get("title")??"").trim(),sourceType=String(form.get("source_type")??"").trim(),identifierType=String(form.get("identifier_type")??"").trim(),identifierValue=String(form.get("identifier_value")??"").trim(),versionLabel=String(form.get("version_label")??"").trim(),language=String(form.get("source_language")??"").trim();if(!title||!sourceType||!identifierType||!identifierValue||!versionLabel||!language)throw new Error("All source identity fields are required");const sourceId=newCanonicalId("source"),versionId=newCanonicalId("sourceVersion");fail((await client.from("authoring_sources").insert({source_id:sourceId,title,source_type:sourceType,identifier_type:identifierType,identifier_value:identifierValue,source_language:language,created_by:user.id})).error);fail((await client.from("authoring_source_versions").insert({source_version_id:versionId,source_id:sourceId,version_label:versionLabel,created_by:user.id})).error);const file=form.get("pdf");if(file instanceof File&&file.size){if(file.type!=="application/pdf")throw new Error("Private upload must be a PDF");const bytes=Buffer.from(await file.arrayBuffer()),hash=createHash("sha256").update(bytes).digest("hex"),fileId=newCanonicalId("sourceFile"),objectPath=`${user.id}/${fileId}.pdf`,bucket=authoringSetup().bucket;fail((await client.storage.from(bucket).upload(objectPath,bytes,{contentType:"application/pdf",upsert:false})).error);fail((await client.from("authoring_source_files").insert({source_file_id:fileId,source_version_id:versionId,source_id:sourceId,object_path:objectPath,sha256:hash,byte_length:bytes.length,created_by:user.id})).error)}await audit(client,user.id,"source.created","source",sourceId,{sourceVersionId:versionId,privatePdf:Boolean(file instanceof File&&file.size)});return sourceId}
export async function createEvidenceRevision(form:FormData,correctionOf?:string){const{client,user}=await requireAuthoringUser();const sourceId=String(form.get("source_id")),versionId=String(form.get("source_version_id")),quotation=String(form.get("exact_quotation")??"").trim(),anchor=String(form.get("text_anchor")??"").trim();if(!quotation||!anchor)throw new Error("Exact quotation and text anchor are required");let evidenceId=newCanonicalId("evidence"),revision=1,predecessor:null|string=null;if(correctionOf){const{data,error}=await client.from("authoring_evidence_revisions").select("*").eq("revision_ref",correctionOf).single();fail(error);if(!data)throw new Error("Revision not found");evidenceId=data.evidence_item_id;revision=data.revision_number+1;predecessor=data.revision_ref}const revisionRef=`${evidenceId}@r${revision}`;const row={revision_ref:revisionRef,evidence_item_id:evidenceId,revision_number:revision,predecessor_ref:predecessor,source_id:sourceId,source_version_id:versionId,exact_quotation:quotation,printed_page:String(form.get("printed_page")??"").trim()||null,pdf_page:Number(form.get("pdf_page"))||null,section_or_recommendation:String(form.get("section_or_recommendation")??"").trim()||null,text_anchor:anchor,table_location:String(form.get("table_location")??"").trim()||null,figure_location:String(form.get("figure_location")??"").trim()||null,interpretation:String(form.get("interpretation")??"").trim(),limitation:String(form.get("limitation")??"").trim(),authority_type:String(form.get("authority_type")),verification_status:String(form.get("verification_status")),review_lifecycle:"pending",created_by:user.id};fail((await client.from("authoring_evidence_revisions").insert(row)).error);await audit(client,user.id,correctionOf?"evidence.corrected":"evidence.created","evidence_revision",revisionRef,{sourceId,predecessor});return revisionRef}
export async function reviewEvidenceRevision(form:FormData){const{client,user}=await requireAuthoringUser();const revisionRef=String(form.get("revision_ref")),sourceId=String(form.get("source_id")),decision=String(form.get("decision")),reviewer=String(form.get("reviewer_name")??"").trim(),date=String(form.get("review_date")??""),confirmed=form.get("original_source_confirmed")==="on",note=String(form.get("reviewer_note")??"").trim();if(!["pending","approved","needs_correction","excluded"].includes(decision)||!reviewer||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("Decision, reviewer, and valid date are required");if(decision==="approved"&&!confirmed)throw new Error("Approved requires original-source confirmation");const reviewId=newCanonicalId("review");fail((await client.from("authoring_specialist_reviews").insert({review_id:reviewId,revision_ref:revisionRef,source_id:sourceId,decision,reviewer_name:reviewer,review_date:date,original_source_confirmed:confirmed,reviewer_note:note,created_by:user.id})).error);await audit(client,user.id,"review.recorded","evidence_revision",revisionRef,{sourceId,reviewId,decision});return reviewId}
